name: Docker Image CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Build the Docker image
        run: |
          docker version
          # 登录阿里云镜像仓库
          docker login --username=13703953153 --password=dk2024aly registry.cn-hangzhou.aliyuncs.com
          cd imgkic
          # 使用Dockerfile构建镜像
          docker build . --file Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/lx2019/imgkic:2.4.1
          # 推送镜像到镜像仓库
          docker push registry.cn-hangzhou.aliyuncs.com/lx2019/imgkic:2.4.1
